### ISSUE TITLE
Bluetooth  version: left side is not responding after awakening from sleep mode

### ISSUE THREAD

**Issue by nilokillian** [280Zo/charybdis-wireless-mini-zmk-firmware#12]
Fairly new to zmk. Got a board based on NRF52840. After awakening from sleep mode, left side is unresponsive , left side got a bit laggy. Off/On for the left side solves the issue

**Comment by 280Zo** [comment]
Thanks for the heads up, nilokillian. Can you give the firmware in the [fix/left-side-wake](https://github.com/280Zo/charybdis-wireless-mini-zmk-firmware/tree/fix/left-side-wake) branch a try? I've added wakeup-source; in the charybdis.dtsi kscan which should help.

**Comment by nilokillian** [comment]
firmware from fix/left-side-wake works well. The issue didn't not occur.  Thank you
